config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # 장고에서 import 해야함 from . 이렇게 하지말고
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),  # users/urls.py 만들고 여기 작성
    path(
        "reservations/", include("reservations.urls", namespace="reservations")
    ),  # reservations/urls.py 만들고 여기 작성
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:  # 개발환경일때는 DEBUG = TRUE라서 이게 작동, 라이브에서는 안돌아가게 할 것
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"  # config에 있는 urls.py에 있는 urlpatterns의 spacename 과 일치해야한다

# urlpatterns 변수명은 필수, 옵션이 아님
urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]
# rooms 어플폴더에서 views.py 파일을 room_views라는 이름으로 import 해놓은 경로로 가져와서 그안 에 있는 all_rooms 함수를 실행시킨것

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]
# 각 룸 id를 url뒤에 붙여서 링크연결되도록
# 두번째 인자로 views.room_detail, 넣는게 function 방식으로 reviews만든 것
# views에서 render하고 html 만들고 여기에 path추가

users/urls.py
from django.urls import path
from . import views  # 같은폴더에 있는 views.py 불러오는거지

app_name = "users"  # config urls.py에 넣고나면 app_name 없다고 오류남 그때 이거 작성
urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete_verification"
    ),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
    path("switch-language/", views.switch_language, name="switch-language"),
]
# 위랑 다른 이유: log_out이 import logout에서 가져온 함수이기 때문
#   # urls.py작업해주고 config urls.py 에 추가하기

templates/partials/footer.html
{% load i18n %}
<footer class="container w-full mx-auto text-center py-5 border-t font-medium text-gray-400">
    <div class="flex flex-col">
        <span>
            {% trans "Please don't copy us" %}
        </span>
        <span>&copy; 2021 Fairy Cake, Inc. {% trans 'All right reserved' %}.</span>
    </div>
    <div class="mt-10 flex">
        {% get_current_language as LANGUAGE_CODE %}
        <select class="w-1/5 h-10" id="js-lang">
            <option value="en" 
                {% if LANGUAGE_CODE == 'en' %}
                    selected
                {% endif %}
                >English</option>
            <option value="es" 
                {% if LANGUAGE_CODE == 'es' %}
                    selected
                {% endif %}
                >Spanish</option>
        </select>
    </div>
</footer>

templates/partials/messages.html
{% if messages %}
    <ul class="absolute top-0 mx-auto left-0 right-0 flex justify-center">
        {% for message in messages %}
        <li class="message font-medium bg-gray-600 z-10 rounded-full text-white py-4 px-6 w-64 text-center {% if message.tags %}{{ message.tags }}{% endif %}">{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

templates/partials/nav.html
<ul class="flex items-center text-xs font-medium h-full">
    {% if user.is_authenticated %}
        <li class="nav_link">
            <a href="{% url 'users:switch-hosting' %}">
                {% if request.session.is_hosting %}
                    <span class="text-red-400">Stop Hosting</span>
                {% else %}
                    <span class="text-green-400">Start Hosting</span>
                {% endif %}
            </a>
        </li>
        {% if request.session.is_hosting %}
            <li class="nav_link text-green-400"><a href="{% url 'rooms:create' %}">Create Room</a></li>    
        {% endif %}

        <li class="nav_link"><a href="{{user.get_absolute_url}}">Profile</a></li>    
        <li class="nav_link"><a href="{% url 'users:logout' %}">Log out</a></li>    
    {% else %}
        <li class="nav_link"><a href="{% url 'users:login' %}">Log in</a></li>
        <li class="nav_link"><a href="{% url 'users:signup' %}">Sign up</a></li>
    {% endif %}
        
</ul>

templates/partials/social_login.html
<div class="flex flex-col w-full">
    <a href="{% url 'users:github-login' %}" class="btn mb-2 border">
       <i class="fab fa-github mr-2 fa-lg"></i> Continue with Github
    </a>
    <a href="{% url 'users:kakao-login' %}" class="btn mb-2 border  bg-yellow-200">
        <i class="fas fa-comment mr-2 fa-lg"></i> Continue with Kakao
    </a>
</div>

<div class="flex items-center w-full my-6">
    <div class="h-px w-full bg-gray-400"></div>
    <span class="text-gray-600 font-medium mx-4 text-sm">or</span>
    <div class="h-px w-full bg-gray-400"></div>
</div>