config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # 장고에서 import 해야함 from . 이렇게 하지말고
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),  # users/urls.py 만들고 여기 작성
    path(
        "reservations/", include("reservations.urls", namespace="reservations")
    ),  # reservations/urls.py 만들고 여기 작성
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:  # 개발환경일때는 DEBUG = TRUE라서 이게 작동, 라이브에서는 안돌아가게 할 것
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"  # config에 있는 urls.py에 있는 urlpatterns의 spacename 과 일치해야한다

# urlpatterns 변수명은 필수, 옵션이 아님
urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]
# rooms 어플폴더에서 views.py 파일을 room_views라는 이름으로 import 해놓은 경로로 가져와서 그안 에 있는 all_rooms 함수를 실행시킨것

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]
# 각 룸 id를 url뒤에 붙여서 링크연결되도록
# 두번째 인자로 views.room_detail, 넣는게 function 방식으로 reviews만든 것
# views에서 render하고 html 만들고 여기에 path추가

rooms/models.py
from django.utils import timezone
from django.db import models
from django.urls import reverse
from django_countries.fields import CountryField
from core import models as core_models  # import 이후 위에거랑 이름 같으니 as 로 명시해주는 것
from cal import Calendar


class AbstractItem(core_models.TimeStampedModel):

    """ Absotract Item """

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):

    """RoomType Model Definition"""

    class Meta:
        verbose_name = "Room Type"
        ordering = ["name"]  # 이름기준 기준으로 순서정리 - 문서에서 ordering 검색


class Amenity(AbstractItem):

    """Amenity Model Definition"""

    class Meta:
        verbose_name_plural = "Amenities"


class Facility(AbstractItem):

    """Facility Model Definition"""

    class Meta:
        verbose_name_plural = "Facilities"


class HouseRule(AbstractItem):

    """ HouseRule Model Definition"""

    class Meta:
        verbose_name = "House Rule"


class Photo(core_models.TimeStampedModel):

    """ Photo Model Definition """

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="room_photos")  # 파일 업로드시 저장될 경로 지정
    room = models.ForeignKey("Room", related_name="photos", on_delete=models.CASCADE)

    def __str__(self):
        return self.caption


class Room(core_models.TimeStampedModel):

    """ Room Model Definition """

    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    guests = models.IntegerField()
    beds = models.IntegerField()
    bedrooms = models.IntegerField()
    baths = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    instant_book = models.BooleanField(default=False)
    host = models.ForeignKey(
        "users.User", related_name="rooms", on_delete=models.CASCADE
    )  # on_delete 삭제행동이 진행되는데 User가 삭제되면 연결된 room도 연쇄삭제(cascade)
    room_type = models.ForeignKey(
        "RoomType", related_name="rooms", on_delete=models.SET_NULL, null=True
    )
    amenities = models.ManyToManyField("Amenity", related_name="rooms", blank=True)
    facilities = models.ManyToManyField("Facility", related_name="rooms", blank=True)
    house_rules = models.ManyToManyField("HouseRule", related_name="rooms", blank=True)

    def __str__(self):
        return self.name  # list 에서 보일 이름을 룸 명으로 지정했던걸로 가져오는 것 / 기존에는 room_object_1 이런식

    # model에서 들어오는걸 덮어쓰기하는거! 이거 잘알아야겠음. 내가 원하는 형태로 변경 가능 - 사람들이 입력한걸 다 대문자로 바꾼다던지 - 통일화에 좋다
    def save(
        self, *args, **kwargs
    ):  # super()로 부모 속성에 접근하는 것 / 도시를 쓰고 save 했을때 그것을 받아서 새로운걸로 덮어쓸거야. super()에는 원래 입력한게 남겠지
        self.city = str.capitalize(self.city)
        super().save(*args, **kwargs)

    def get_absolute_url(self):  # 내가 원하는 model을 찾을 수 있는 url을 주는 것
        return reverse("rooms:detail", kwargs={"pk": self.pk})
        # rooms는 config->urls.py->urlpatterns->namespace 에 있는 rooms
        # detail은 rooms->urls.py->urlpatterns->name에 있는 detail
        # admin에서 각 room에 들어갔을때 우측에 나오는  view on site를 만들어주는 것

    def total_rating(self):
        all_reviews = self.reviews.all()
        all_ratings = 0
        if len(all_reviews) > 0:
            for review in all_reviews:
                all_ratings += review.rating_average()
            return round(all_ratings / len(all_reviews), 2)
        return 0

    def first_photo(self):
        try:
            (photo,) = self.photos.all()[:1]
            return photo.file.url
            # 뒤에 , 붙여주면 arrey에서 첫번째 요소만 원한다는걸 알고 보내줌
        except ValueError:
            return None

    def get_next_four_photos(self):
        photos = self.photos.all()[1:5]
        return photos

    def get_calendars(self):
        now = timezone.now()
        this_year = now.year
        this_month = now.month
        next_month = this_month + 1
        if this_month == 12:
            next_month = 1
        this_month_cal = Calendar(this_year, this_month)
        next_month_cal = Calendar(this_year, next_month)
        return [this_month_cal, next_month_cal]

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):

    city = forms.CharField(initial="Anywhere")
    country = CountryField(default="KR").formfield()
    room_type = forms.ModelChoiceField(
        required=False, empty_label="Any Kind", queryset=models.RoomType.objects.all()
    )
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )
    facilities = forms.ModelMultipleChoiceField(
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False,
    )


class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        template_name = "rooms/photo_create.html"
        fields = ("caption", "file")

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()


class CreateRoomForm(forms.ModelForm):
    class Meta:
        model = models.Room
        fields = (
            "name",
            "description",
            "country",
            "city",
            "price",
            "address",
            "guests",
            "beds",
            "bedrooms",
            "baths",
            "check_in",
            "check_out",
            "room_type",
            "amenities",
            "facilities",
            "house_rules",
        )

    def save(self, *args, **kwargs):
        room = super().save(
            commit=False
        )  # commit=False 때문에 오브젝트는 생성하지만 데이터베이스에 넣지는 않는다
        return room

rooms/views.py
from django.http import Http404
from django.views.generic import ListView, DetailView, UpdateView, FormView, View
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, reverse
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from users import mixins as user_mixins
from . import models, forms

# 밑에 둘은 function기반으로할때 사용
# from django.http import Http404
# from django.shortcuts import render, redirect
# from django.urls import reverse


class HomeView(ListView):  # core폴더의 url에도 넣어뒀음

    """ HomeView Definition """

    model = models.Room
    paginate_by = 12  # ListView 관련사항 ccv.co.uk확인하면 잘 정리되어있음
    paginate_orphans = 5
    ordering = "created"
    context_object_name = "rooms"


# class 기반 views
class RoomDetail(
    DetailView
):  # DetailView 사용하면 django가 기본적으로 url argument로 pk를 찾는다 urls.py에 있는 int:pk

    """ RoomDetail Definition """

    model = models.Room


# function 기반으로 views 만든 것
# def room_detail(request, pk):  # pk가 room id이고 url 뒤에 붙겍되는건지
#     try:
#         room = models.Room.objects.get(pk=pk)  # 데이터베이스에서 룸 정보를 가져오기 위해
#         return render(request, "rooms/detail.html", {"room": room})
#     except models.Room.DoesNotExist:  # 예외처리하기 위해서, pk넘버에 없는걸 주소에 넣으면 이쪽으로 처리되도록
#         # return redirect(reverse("core:home"))  # url대신 reverse 써서 하는걸 추천, 홈으로 보내주는거
#         raise Http404()  # 오류는 return이 아니라 raise사용 #404띄우면 따로 저장안하니까 이렇게 써도 괜찮지
#         # setting.py 에서 DEBUG = False, ALLOWED_HOST = "*" 해야지만 이 templates에 있는 404.html을 볼 수 있다


class SearchView(View):

    """ Search View Definition"""

    def get(self, request):
        country = request.GET.get("country")
        if country:
            form = forms.SearchForm(
                request.GET
            )  # request.GET 넣어서 서치버튼 눌렀을때 설정 기억하도록하는 것
            if form.is_valid():  # if 오류가 없다면
                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                bedrooms = form.cleaned_data.get("bedrooms")
                beds = form.cleaned_data.get("beds")
                baths = form.cleaned_data.get("baths")
                instant_book = form.cleaned_data.get("instant_book")
                superhost = form.cleaned_data.get("superhost")
                amenities = form.cleaned_data.get("amenities")
                facilities = form.cleaned_data.get("facilities")

                filter_args = {}

                if city != "Anywhere":
                    filter_args["city__startswith"] = city

                filter_args["country"] = country

                if room_type is not None:
                    filter_args["room_type"] = room_type

                if price is not None:
                    filter_args["price__lte"] = price  # lte 작거나 같음

                if guests is not None:
                    filter_args["guests__gte"] = guests  # gte 크거나 같음

                if bedrooms is not None:
                    filter_args["bedrooms__gte"] = bedrooms

                if beds is not None:
                    filter_args["beds__gte"] = beds

                if baths is not None:
                    filter_args["baths__gte"] = baths

                if instant_book is True:
                    filter_args["instant_book"] = True  # moelds.py에 있는 instant_book 이름

                if superhost is True:
                    filter_args["host__superhost"] = True

                for amenity in amenities:
                    filter_args["amenities"] = amenity

                for facility in facilities:
                    filter_args["facilities"] = facility

                qs = models.Room.objects.filter(**filter_args).order_by("-created")

                paginator = Paginator(qs, 10, orphans=5)

                page = request.GET.get("page", 1)

                rooms = paginator.get_page(page)

                return render(
                    request, "rooms/search.html", {"form": form, "rooms": rooms}
                )

        else:
            form = forms.SearchForm()
            # 첫form을 가져와야할때(데이터확인과정없는 순간)  request.GET아닌걸로 연결해서 required 안뜨게 하는거
        return render(request, "rooms/search.html", {"form": form})


class EditRoomView(user_mixins.loggedInOnlyView, UpdateView):
    model = models.Room
    template_name = "rooms/room_edit.html"
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "room_type",
        "amenities",
        "facilities",
        "house_rules",
    )
    # 보안을 위해, 내방아닌데 url에 edit치고 들어오면 안되니까 로그인 유저랑 방주인이랑 맞는지 pk로 확인
    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room


class RoomPhotosView(user_mixins.loggedInOnlyView, DetailView):

    model = models.Room  # 결국 이게 위에 있는 RoomDetail 이지
    template_name = "rooms/room_photos.html"

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404()
        return room


@login_required
def delete_photo(request, room_pk, photo_pk):
    user = request.user
    try:
        room = models.Room.objects.get(pk=room_pk)
        if room.host.pk != user.pk:
            messages.error(request, "Cant delete that photo")
        else:
            models.Photo.objects.filter(pk=photo_pk).delete()
            messages.success(request, "photo Deleted")
            return redirect(reverse("rooms:photos", kwargs={"pk": room_pk}))
    except models.Room.DoesNotExist:
        return redirect(reverse("core:home"))


class EditPhotoView(user_mixins.loggedInOnlyView, SuccessMessageMixin, UpdateView):

    model = models.Photo
    template_name = "rooms/photo_edit.html"
    pk_url_kwarg = "photo_pk"  # 원래 그냥 pk를찾게되는데 여기 위에서 photo_pk로해놔서 이렇게해줘야함
    success_message = "Photo updated"
    fields = ("caption",)  # fields는 항상 리스트나 튜플식으로 되어야하기 때문에 스트링이면 오류날거야. 하나라도 이렇게해둘 것

    def get_success_url(self):
        room_pk = self.kwargs.get("room_pk")
        print(room_pk)
        return reverse("rooms:photos", kwargs={"pk": room_pk})


class AddPhotoView(user_mixins.loggedInOnlyView, FormView):

    template_name = "rooms/photo_create.html"
    fields = ("caption", "file")
    form_class = forms.CreatePhotoForm  # forms.py에 있음

    def form_valid(self, form):
        pk = self.kwargs.get("pk")
        form.save(pk)
        messages.success(self.request, "Photo Uploaded")
        return redirect(reverse("rooms:photos", kwargs={"pk": pk}))


class CreateRoomView(user_mixins.loggedInOnlyView, FormView):
    form_class = forms.CreateRoomForm
    template_name = "rooms/room_create.html"

    def form_valid(self, form):
        room = form.save()
        room.host = self.request.user
        room.save()
        form.save_m2m()  # 위에 room.save()로 데이터베이스에 저장한 후에 이걸해야함 many to many form 저장하기 위해서
        messages.success(self.request, "Room Created")
        return redirect(reverse("rooms:detail", kwargs={"pk": room.pk}))

templates/rooms/detail.html
{%extends "base.html" %}


{% block page_name%}
    Home
{% endblock page_name%}


{% block content %}
<div>    
    <h1>{{room.name}}</h1>
    <h3>{{room.description}}</h3>
</div>
<div>
    <h2>By : {{room.host.username}}
        
        {% if room.host.superhost %} <!--슈퍼호스트면 표시되도록 한것-->
            (superhost)
        {% endif %}
    </h2>
    <h3>Amenities</h3>
    <ul>
        {% for a in room.amenities.all %}
            <li>{{a}}</li>
        {% endfor %}
    </ul>
    <h3>Facilities</h3>
    <ul>
        {% for f in room.facilities.all %}
            <li>{{f}}</li>
        {% endfor %}
    </ul>
    <h3>House Rules</h3>
    <ul>
        {% for r in room.house_rules.all %}
            <li>{{r}}</li>
        {% endfor %}
    </ul>
</div>
{% endblock  %}
    

templates/rooms/photo_create.html
{% extends 'base.html' %}


{% block page_title %}
    Add Photo
{% endblock page_title %}
    
{% block search-bar %} 
{% endblock search-bar %}

    

{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border border-gray-400 p-6">
        
        {% include 'mixins/room/room_form.html' with form=form cta="Add Photo"%}
        
    </div>
{% endblock content %}
    

templates/rooms/photo_edit.html
{% extends 'base.html' %}


{% block page_title %}
    Edit Photo
{% endblock page_title %}
    
{% block search-bar %} 
{% endblock search-bar %}

    

{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border border-gray-400 p-6">
        
        {% include 'mixins/room/room_form.html' with form=form cta="Edit Photo"%}
        
    </div>
{% endblock content %}
    

templates/rooms/room_create.html
{% extends 'base.html' %}


{% block page_title %}
    Create Room
{% endblock page_title %}
    
{% block search-bar %} 
{% endblock search-bar %}

    

{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border border-gray-400 p-6">
        {% include 'mixins/room/room_form.html' with form=form cta="Create Room"%}
    </div>
{% endblock content %}
    

templates/rooms/room_detail.html
{%extends "base.html" %}
{% load is_booked %}

{% block page_title%}
    {{room.name}}
{% endblock page_title%}


{% block content %}
    <div class="container max-w-full h-75vh flex mb-20 -mt-5">
        <div class="h-full w-1/2 bg-cover bg-center border border-gray-400" style="background-image:url({{room.first_photo}})"></div>
        <div class="h-full w-1/2 flex flex-wrap">
            
            {% for photo in room.get_next_four_photos  %}
                <div class="bg-cover bg-center w-1/2 h-auto border border-gray-400" style="background-image:url({{photo.file.url}})"></div>
            {% endfor %}
    
        </div>
    </div>

    <div class="container mx-auto flex justify-around pb-56">
        <div class="w-1/2">
            <div class="flex justify-between">
                <div class="mb-5">
                    <h4 class="text-3xl font-medium mb-px">{{room.name}}</h4>
                    <span class="text-gray-500 font-light">{{room.city}}</span>
                </div>
                <a href="{{room.host.get_absolute_url}}" class="flex flex-col justify-center items-center">
                    {% include "mixins/user_avatar.html" with user=room.host %}
                    <span class="mt-2 text-gray-500">{{room.host.first_name}}</span>
                </a>
            </div>
            <div class="flex font-medium border-section">
                <span class="mr-5">{{room.room_type}}</span>
                <span class="mr-5">{{room.guests}} guest{{room.guests|pluralize}}</span>
                <span class="mr-5">{{room.bedrooms}} bedroom{{room.bedrooms|pluralize}}</span>
                <span class="mr-5">{{room.beds}} bed{{room.beds|pluralize}}</span> <!--pluralize 통해서 복수일때 s 붙음-->
                <span class="mr-5">{{room.baths}} bath{{room.baths|pluralize}}</span>
            </div>
            <p class="border-section">
                {{room.description}}
            </p>
            <div class="border-section">
                <h4 class="font-medium text-lg mb-5">Amenities</h4>
                {% for a in room.amenities.all  %}
                    <li class="mb-2">{{a}}</li>
                {% endfor %} 
            </div>
            <div class="border-section">
                <h4 class="font-medium text-lg mb-5">Facilities</h4> 
                {% for f in room.facilities.all  %}
                    <li class="mb-2">{{f}}</li>
                {% endfor %}
            </div>
            <div class="border-section">
                <h4 class="font-medium text-lg mb-5">House Rules</h4> 
                {% for h in room.house_rules.all  %}
                    <li class="mb-2">{{h}}</li>
                {% endfor %}
            </div>
            <div class="mt-5">
                <h4 class="font-medium text-2xl mb-5">Reviews</h4>
                <div class="flex items-center">
                    <div class="flex items-center">
                        <i class="fas fa-star text-red-400 mr-2"></i>
                        <span class="font-bold text-xl">{{room.total_rating}}</span>
                    </div>
                    <div class="h-5 w-px bg-gray-400 mx-5"></div>
                    <div>
                        <span class="font-bold text-xl">{{room.reviews.count}}</span>
                        <span>review{{room.reviews.count|pluralize}}</span>
                    </div>
                </div>
                <div class="mt-5">
                    {% for review in room.reviews.all %}
                    <div class="border-section">
                        <div class="flex items-center mb-3">
                            <div>
                                {% include 'mixins/user_avatar.html' with user=review.user h_and_w='h-10 w-10' text='text-lg' %}
                            </div>
                            <div class="flex flex-col ml-5">
                                <span class="font-medium">{{review.user.first_name}}</span>
                                <span class="text-sm text-gray-500">{{review.created|date:'F Y'}}</span>
                            </div>
                        </div>
                        <span>{{review.review}}</span>
                    </div>
                    {% endfor %}   
                </div>
            </div>
        </div>
        <div class="w-1/3">
            
            {% if room.host == user %}
                <a href="{% url 'rooms:edit' room.pk %}" class="btn-link block">Edit Room</a>
            {% else %}
                {% if not request.session.is_hosting %}    
                    {% for calendar in room.get_calendars  %}
                    <div class="mb-20">
                        <span class="text-center font-medium text-lg block mb-6">{{calendar.get_month}} / {{calendar.year}}</span>
                        <div class="cal-grid font-semibold mb-4">
                            {% for day in calendar.day_names %}
                                <span>{{day}}</span>
                            {% endfor %}
                        </div>
                        <div class="cal-grid">
                            {% for day in calendar.get_days  %}
                                {% is_booked room day as is_booked_bool %}
                                {% if day.number != 0 %}
                                    
                                    {% if day.past %}
                                        <span class="bg-gray-100 w-full text-center rounded text-gray-300 p-1">{{day}}</span>
                                    {% elif is_booked_bool %}
                                        <span class="bg-gray-100 w-full text-center rounded text-gray-300 p-1 line-through">{{day}}</span>
                                    {% else%}
                                        <a href="{% url 'reservations:create' room.pk day.year day.month day.number %}" class="bg-gray-100 w-full text-center rounded text-gray-700 p-1 hover:bg-green-400 hover:text-white cursor-pointer">{{day}}</a>
                                    {% endif %}
                                            
                                
                                {% else %}
                                    <span></span>
                                {% endif %}
                                    
                            {% endfor %}       
                        </div>
                    </div>
                    {% endfor %}        
                {% endif %}
            {% endif %}
            
        </div>
    </div>

{% endblock  %}
    

templates/rooms/room_edit.html
{% extends 'base.html' %}


{% block page_title %}
    Edit Room
{% endblock page_title %}
    
{% block search-bar %} 
{% endblock search-bar %}

    

{% block content %}
    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border border-gray-400 p-6">
        
        {% include 'mixins/room/room_form.html' with form=form cta="Edit Room"%}

        <div class="mt-2">
            <a href="{% url 'rooms:photos' room.pk %}" class="text-red-400 font-medium">Edit Photos</a>
        </div>
        
    </div>
{% endblock content %}
    

templates/rooms/room_list.html
{%extends "base.html" %}


{% block page_title%}
Home
{% endblock page_title%}


{% block content %}

    <div class="container mx-auto mb-14">

        <div class="rounded-xl bg-gray-800 h-50vh mt-32 mb-16 bg-cover bg-center" style="background-image:url(https://images.unsplash.com/photo-1517166988974-5e377975dd67?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1721&q=80)"></div>
        <div class="flex flex-wrap">
            {% for room  in rooms  %}
                {% include 'mixins/room_card.html' with room=room %}<!-- room=room에서 뒤에 room이 for문에서 받은 room -->
            {% endfor %}
        </div>
        <div class="flex items-center justify-center">
            {% if page_obj.has_previous %} 
                <a href="?page={{page_obj.previous_page_number}}" class="text-red-400">
                    <i class="fas fa-arrow-left text-red-400 fa-lg"></i>
                </a>    
            {% endif %}
            
            <span class="mx-10 font-medium">{{page_obj.number}} of {{page_obj.paginator.num_pages}}</span>

            {% if page_obj.has_next %}
                <a href="?page={{page_obj.next_page_number}}" class="text-red-400">
                    <i class="fas fa-arrow-right fa-lg"></i>
                </a>    
            {% endif %}
        </div>


    </div>



{% endblock content %}



    

templates/rooms/room_photos.html
{% extends 'base.html' %}


{% block page_title %}
    {{room.name}}'s Photos
{% endblock page_title %}
    
{% block search-bar %} 
{% endblock search-bar %}

    

{% block content %}
    <div class="container mx-auto my-10 flex flex-col">
        <div class="my-5">
            <a href="{% url 'rooms:add-photo' room.pk %}" class="btn-link w-1/6 block">Upload Photo</a>
        </div>

        {% for photo in room.photos.all  %}
            <div class="flex justify-between items-center mb-5 border border-gray-400 p-6">
                <div class="flex items-start">
                    <img src="{{photo.file.url}}" class="w-32 h-32">
                    <span class="ml-5 text-xl font-medium">{{photo.caption}}</span>
                </div>
                <div class="flex flex-col w-1/5">
                    <a href="{% url 'rooms:edit-photo' room.pk photo.pk %}" class="btn-link mb-5 bg-green-400">Edit</a>
                    <a href="{% url 'rooms:delete-photo' room.pk photo.pk %}" class="btn-link mb-5 bg-red-600">Delete</a>
                </div>
            </div>
            
        {% endfor %}
        <div class="flex justify-center mt-5"> 
            <a class=" text-green-400 font-medium" href="{% url 'rooms:edit' room.pk %}">Back to edit room</a>
        </div>
    </div>
{% endblock content %}
    

templates/rooms/search.html
{% extends 'base.html' %}


{% block page_title %}
    Search
{% endblock page_title %}
    
<!--base에 따로 search-bar 만들어놓고 모든페이지에 뜨게한뒤 , 여기 서치에서는 서치를 볼필요 없으니 밑에 빈 블럭으로 만들어서 숨기는 것
그렇게하고 밑에 있는 블럭에서 새롭게 같은형식으로 만들어 두기-->
{% block search-bar %} 
{% endblock search-bar %}

    

{% block content %}

    <h2>Search!</h2>

    <form method="get" action="{% url 'rooms:search' %}">
        {{form.as_p}}        
        <button>Search</button>
    </form> 

    <h3>Results</h3>
    
    {% for room in rooms %}
        <h3>{{room.name}}</h3>        
    {% endfor %}
        


{% endblock content %}
    