config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # 장고에서 import 해야함 from . 이렇게 하지말고
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),  # users/urls.py 만들고 여기 작성
    path(
        "reservations/", include("reservations.urls", namespace="reservations")
    ),  # reservations/urls.py 만들고 여기 작성
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:  # 개발환경일때는 DEBUG = TRUE라서 이게 작동, 라이브에서는 안돌아가게 할 것
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"  # config에 있는 urls.py에 있는 urlpatterns의 spacename 과 일치해야한다

# urlpatterns 변수명은 필수, 옵션이 아님
urlpatterns = [path("", room_views.HomeView.as_view(), name="home")]
# rooms 어플폴더에서 views.py 파일을 room_views라는 이름으로 import 해놓은 경로로 가져와서 그안 에 있는 all_rooms 함수를 실행시킨것

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>/", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add", views.AddPhotoView.as_view(), name="add-photo"),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/delete/",
        views.delete_photo,
        name="delete-photo",
    ),
    path(
        "<int:room_pk>/photos/<int:photo_pk>/edit/",
        views.EditPhotoView.as_view(),
        name="edit-photo",
    ),
    path("search/", views.SearchView.as_view(), name="search"),
]
# 각 룸 id를 url뒤에 붙여서 링크연결되도록
# 두번째 인자로 views.room_detail, 넣는게 function 방식으로 reviews만든 것
# views에서 render하고 html 만들고 여기에 path추가

users/urls.py
from django.urls import path
from . import views  # 같은폴더에 있는 views.py 불러오는거지

app_name = "users"  # config urls.py에 넣고나면 app_name 없다고 오류남 그때 이거 작성
urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("login/github/", views.github_login, name="github-login"),
    path("login/github/callback/", views.github_callback, name="github-callback"),
    path("login/kakao/", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback/", views.kakao_callback, name="kakao-callback"),
    path("logout/", views.log_out, name="logout"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "verify/<str:key>/", views.complete_verification, name="complete_verification"
    ),
    path("update-profile/", views.UpdateProfileView.as_view(), name="update"),
    path("update-password/", views.UpdatePasswordView.as_view(), name="password"),
    path("<int:pk>/", views.UserProfileView.as_view(), name="profile"),
    path("switch-hosting/", views.switch_hosting, name="switch-hosting"),
    path("switch-language/", views.switch_language, name="switch-language"),
]
# 위랑 다른 이유: log_out이 import logout에서 가져온 함수이기 때문
#   # urls.py작업해주고 config urls.py 에 추가하기

templates/base.html
{% load static i18n%}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <!--font-awesome 가져오기-->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
        <!--css 가져온다-->
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        
        <title> 
            {% block page_title%}{% endblock page_title%} | Nbnb
        </title>
    </head>
    <body class="text-gray-800 mt-24 font-light">
        {% include "partials/messages.html" %}
        <header class="container max-w-full inset-0 flex items-center justify-between px-6 h-20 border-b border-gray-200 fixed bg-white inset-0">
            <div class="flex items-center w-1/2">
                <a href="{% url 'core:home' %}" class="mr-6">
                    <img class="w-16" src="{% static 'img/logo.png' %}" />
                </a>
                {% block search-bar %}    
                <form method="get" action="{% url 'rooms:search' %}" class="w-9/12">
                    <input 
                    class="search-box border w-9/12 px-5 py-2 text-sm font-medium placeholder-gray-500 rounded-lg shadow-md hover:shadow-lg focus:outline-none"
                    name="city"
                    placeholder="{% trans 'Search by City' %}"
                    />
                    <button class="ml-3"><i class="fas fa-search"></i></button>
                </form> 
                {% endblock search-bar %}
            </div>
            {% include "partials/nav.html" %}
        </header>


        {% block content %}{% endblock %}    <!-- block으로 해놓은 곳 안으로 자식 html들이 들어가게됨 -->

        {% include "partials/footer.html"%}
        <script>
            const langSelect = document.getElementById("js-lang");
            const handleLangChange = () => {
                const selected = langSelect.value;
                fetch(`{% url 'users:switch-language' %}?lang=${selected}`).then(() => window.location.reload());
                window.location.reload();
            }
            langSelect.addEventListener("change", handleLangChange);
        </script>
    </body>
</html>